# Generated by Django 4.1.5 on 2023-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('vaccinated', models.BooleanField()),
            ],
        ),
    ]
