# Generated by Django 4.1.5 on 2023-06-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
