# Generated by Django 4.1.5 on 2023-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
