# Generated by Django 4.1.5 on 2023-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_remove_dog_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vaccinated',
            field=models.BooleanField(default=True),
        ),
    ]
