# Generated by Django 4.1.5 on 2023-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dog_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
