# Generated by Django 4.1.5 on 2023-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_alter_dog_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs_photo/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
