# Generated by Django 4.1.5 on 2023-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_alter_dog_children_alter_dog_dog_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='gender',
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
