# Generated by Django 4.1.5 on 2023-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_alter_dog_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=15),
        ),
    ]
